[build-system]
requires = ["setuptools>=64", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "lib-version"
#version = "0.0.1"
dynamic = ["version"]

[tool.setuptools_scm]
tag_regex = "^(?P<version>v[0-9]+(?:\\.[0-9]+)*[^\\s]*?)$"